"""initial Migration

Revision ID: e6bb45d2b79f
Revises: 
Create Date: 2026-01-01 15:01:51.930044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6bb45d2b79f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Create artists table
    op.create_table(
        'artists',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('romaji_name', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),  # optional, but good practice
        sa.PrimaryKeyConstraint('id'),
        sa.Index('idx_artists_name', 'name'),
        sa.Index('idx_artists_romaji', 'romaji_name'),
        sa.Index('idx_artists_created_at', 'created_at')
    )


    # 2. Create genres table
    op.create_table(
        'genres',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.Index('idx_genres_name', 'name')
    )
    # 3. Create albums table
    op.create_table(
        'albums',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('romaji_title', sa.String(), nullable=False),
        sa.Column('release_date', sa.DateTime(), nullable=False),
        sa.Column('artist_id', sa.Integer(), nullable=False),
        sa.Column('album_art', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.Index('idx_albums_title', 'title'),
        sa.Index('idx_albums_romaji', 'romaji_title'),
        sa.Index('idx_albums_release_date', 'release_date'),
        sa.Index('idx_albums_artist_id', 'artist_id')
    )

    # 4. Create songs table
    op.create_table(
        'songs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('romaji_title', sa.String(), nullable=False),
        sa.Column('file_path', sa.String(), nullable=False),
        sa.Column('duration', sa.Integer(), nullable=False),
        sa.Column('track_number', sa.Integer(), nullable=False),
        sa.Column('times_played', sa.Integer(), nullable=False, default=0),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.Index('idx_songs_title', 'title'),
        sa.Index('idx_songs_romaji', 'romaji_title'),
        sa.Index('idx_songs_file_path', 'file_path'),
        sa.Index('idx_songs_duration', 'duration'),
        sa.Index('idx_songs_track_number', 'track_number'),
        sa.Index('idx_songs_times_played', 'times_played'),
        sa.Index('idx_songs_created_at', 'created_at')
    )

    # 5. Create song_artists association table
    op.create_table(
        'song_artists',
        sa.Column('artist_id', sa.Integer(), nullable=False),
        sa.Column('song_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('artist_id', 'song_id'),
        sa.Index('idx_song_artists_artist_id', 'artist_id'),
        sa.Index('idx_song_artists_song_id', 'song_id')
    )

    # 6. Create song_genres association table
    op.create_table(
        'song_genres',
        sa.Column('genre_id', sa.Integer(), nullable=False),
        sa.Column('song_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('genre_id', 'song_id'),
        sa.Index('idx_song_genres_genre_id', 'genre_id'),
        sa.Index('idx_song_genres_song_id', 'song_id')
    )

    # 9. Add album_id column to songs table
    op.add_column('songs', sa.Column('album_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_songs_album_id',
        'songs',
        'albums',
        ['album_id'],
        ['id'],
        ondelete='SET NULL'
    )
    
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
